export type ResourceSubtype =
  'aws_emr_cluster' |
  'aws_mskconnect_connector' |
  'aws_osis_pipeline' |
  'aws_athena_data_catalog' |
  'aws_glue_crawler' |
  'aws_glue_catalog_database' |
  'aws_glue_data_quality_ruleset' |
  'aws_lakeformation_data_lake_settings' |
  'aws_api_gateway_rest_api' |
  'aws_cloudwatch_event_bus' |
  'aws_pipes_pipe' |
  'aws_cloudwatch_event_rule' |
  'aws_scheduler_schedule' |
  'aws_schemas_schema' |
  'aws_schemas_registry' |
  'aws_mq_broker' |
  'aws_sns_topic_subscription' |
  'aws_sns_topic' |
  'aws_sqs_queue' |
  'aws_managedblockchain_member' |
  'aws_sesv2_email_identity' |
  'aws_ami' |
  'aws_autoscaling_group' |
  'aws_eip' |
  'aws_instance' |
  'aws_launch_template' |
  'aws_spot_instance_request' |
  'aws_elastic_beanstalk_application' |
  'aws_elastic_beanstalk_environment' |
  'aws_lambda_function' |
  'aws_ecr_repository' |
  'aws_ecs_cluster' |
  'aws_ecs_service' |
  'aws_ecs_task_definition' |
  'aws_eks_cluster' |
  'aws_rds_cluster_instance' |
  'aws_db_instance' |
  'aws_rds_cluster' |
  'aws_docdbelastic_cluster' |
  'aws_dax_cluster' |
  'aws_dynamodb_table' |
  'aws_elasticache_cluster' |
  'aws_elasticache_replication_group' |
  'aws_db_proxy' |
  'aws_dms_replication_task' |
  'aws_cloud9_environment_ec2' |
  'aws_workspaces_workspace' |
  'aws_workspacesweb_portal' |
  'aws_location_geofence_collection' |
  'aws_location_map' |
  'aws_location_place_index' |
  'aws_location_route_calculator' |
  'aws_location_tracker' |
  'aws_amplify_app' |
  'aws_iot_certificate' |
  'aws_iot_policy' |
  'aws_iotanalytics_channel' |
  'aws_iotanalytics_datastore' |
  'aws_iotanalytics_dataset' |
  'aws_iotanalytics_pipeline' |
  'aws_iotfleethub_application' |
  'aws_greengrassv2_component_version' |
  'aws_iot_topic_rule' |
  'aws_iotsitewise_asset' |
  'aws_iotsitewise_asset_model' |
  'aws_sagemaker_model' |
  'aws_sagemaker_notebook_instance' |
  'aws_cloudwatch_metric_alarm' |
  'aws_oam_link' |
  'aws_cloudwatch_log_data_protection_policy' |
  'aws_evidently_project' |
  'aws_cloudwatch_log_group' |
  'aws_rum_app_monitor' |
  'aws_synthetics_canary' |
  'aws_cloudformation_stack' |
  'aws_cloudtrail_event_data_store' |
  'aws_opsworks_application' |
  'aws_opsworks_instance' |
  'aws_opsworks_permission' |
  'aws_opsworks_stack' |
  'aws_organizations_account' |
  'aws_organizations_organizational_unit' |
  'aws_ssm_document' |
  'aws_ssmincidents_response_plan' |
  'aws_ssm_maintenance_window' |
  'aws_ssm_parameter' |
  'aws_ssm_patch_baseline' |
  'aws_ssm_association' |
  'aws_mediaconnect_gateway' |
  'aws_datasync_agent' |
  'aws_datasync_discovery_job' |
  'aws_m2_environment' |
  'aws_refactorspaces_application' |
  'aws_refactorspaces_environment' |
  'aws_refactorspaces_service' |
  'aws_transfer_connector' |
  'aws_transfer_server' |
  'aws_cloudfront_distribution' |
  'aws_cloudfront_function' |
  'aws_route53recoveryreadiness_readiness_check' |
  'aws_route53_resolver_endpoint' |
  'aws_route53_resolver_firewall_domain_list' |
  'aws_route53_resolver_query_log_config' |
  'aws_route53recoverycontrolconfig_cluster' |
  'aws_route_table' |
  'aws_route53recoverycontrolconfig_routing_control' |
  'aws_route53_zone' |
  'aws_ec2_carrier_gateway' |
  'aws_customer_gateway' |
  'aws_network_interface' |
  'aws_vpc_endpoint' |
  'aws_flow_log' |
  'aws_internet_gateway' |
  'aws_nat_gateway' |
  'aws_ec2_network_insights_analysis' |
  'aws_network_acl' |
  'aws_vpc_peering_connection' |
  'aws_ec2_network_insights_path' |
  'aws_ec2_traffic_mirror_session' |
  'aws_vpc' |
  'aws_vpn_connection' |
  'aws_vpn_gateway' |
  'aws_appmesh_mesh' |
  'aws_appmesh_virtual_gateway' |
  'aws_appmesh_virtual_node' |
  'aws_appmesh_virtual_router' |
  'aws_appmesh_virtual_service' |
  'aws_service_discovery_private_dns_namespace' |
  'aws_service_discovery_service' |
  'aws_networkmanager_core_network' |
  'aws_networkmanager_transit_gateway_route_table_attachment' |
  'aws_dx_gateway' |
  'aws_ec2_transit_gateway_vpc_attachment' |
  'aws_lb' |
  'aws_elb' |
  'aws_acmpca_certificate_authority' |
  'aws_directory_service_directory' |
  'aws_accessanalyzer_analyzer' |
  'aws_rolesanywhere_trust_anchor' |
  'aws_iam_access_key' |
  'aws_iam_virtual_mfa_device' |
  'aws_iam_policy' |
  'aws_iam_role' |
  'aws_kms_custom_key_store' |
  'aws_networkfirewall_firewall' |
  'aws_shield_protection' |
  'aws_wafv2_rule_group' |
  'aws_dlm_lifecycle_policy' |
  'aws_ebs_snapshot' |
  'aws_ebs_volume' |
  'aws_efs_file_system' |
  'aws_fsx_file_cache' |
  'aws_s3_bucket' |
  'aws_s3_access_point' |
  'aws_s3_object' |
  'aws_s3_bucket_intelligent_tiering_configuration' |
  'aws_s3control_multi_region_access_point' |
  'aws_s3control_object_lambda_access_point' |
  'aws_s3_bucket_object_lock_configuration' |
  'aws_s3outposts_endpoint' |
  'aws_s3_bucket_replication_configuration' |
  'aws_s3control_storage_lens_configuration' |
  'aws_glacier_vault' |
  'aws_backup_framework' |
  'aws_backup_plan' |
  'aws_backup_restore_testing_plan' |
  'aws_backup_vault' |
  'aws_backup_report_plan' |
  'aws_backup_gateway_gateway' |
  'aws_backup_legal_hold' |
  'aws_backup_vault_lock_configuration' |
  'aws_storagegateway_cached_iscsi_volume' |
  'aws_storagegateway_gateway' |
  'aws_storagegateway_stored_iscsi_volume' |
  'aws_storagegateway_tape_pool';
export type GroupSubtype = 'region' | 'vpc' | 'az' | 'subnet';

export interface GroupNodeData {
  label: string;
  shortLabel: string;
  subtype: GroupSubtype;
  isSelected?: boolean;
  [key: string]: unknown;
}

export interface ResourceNodeData {
  label: string;
  shortLabel: string;
  subtype: ResourceSubtype;
  arn?: string;
  region?: string;
  vpcId?: string;
  az?: string;
  subnetId?: string;
  tags?: Record<string, string>;
  metrics?: { cpuUsage: number; networkIn: number; networkOut: number };
  isSelected?: boolean;
  [key: string]: unknown;
}

export interface AWSEdgeData {
  label?: string;
  trafficType?: 'http' | 'tcp' | 'database';
  volume?: string;
  [key: string]: unknown;
}
